version: '3.8'
services:
  backend:
    image: library-backend:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_PORT=${APP_PORT:-8080}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/
      - DB_USER=postgres
      - DB_PASS=12345
    restart: unless-stopped

  db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.ru
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-postgres:
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/vitaliy/test/db
  pgadmin-data:
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/vitaliy/test/pgadmin-data