CREATE TABLE Person (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL UNIQUE,
    year_of_birth INT NOT NULL,
    username VARCHAR(100),
    password TEXT
);

CREATE TABLE Book (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    year INT NOT NULL,
    person_id INT REFERENCES Person(id) ON DELETE SET NULL,
    taken_at TIMESTAMP
);

INSERT INTO person (full_name, year_of_birth, username, password) VALUES ('Иванов Иван Иванович', 1968, 'ivan', 123);
INSERT INTO person (full_name, year_of_birth, username, password) VALUES ('Петров Петр Петрович', 1990, 'petr', 245);
INSERT INTO person (full_name, year_of_birth, username, password) VALUES ('Олегов Олег Олегович', 1990, 'oleg', 789);

INSERT INTO book (title, author, year) VALUES ('Бытие и время',	'Мартин Хайдеггер',	1927);
INSERT INTO book (title, author, year) VALUES ('Философия Java', 'Брюс Эккель',	2018);
INSERT INTO book (title, author, year) VALUES ('Игра в бисер', 'Герман Гессе',	1943);
INSERT INTO book (title, author, year) VALUES ('Тайные виды на гору Фудзи',	'Владимир Пелевин',	2018);
INSERT INTO book (title, author, year) VALUES ('Над пропастью во ржи', 'Джером Сэллинджер', 1951);
INSERT INTO book (title, author, year) VALUES ('Психология обыденной жизни', 'Фрейд Зигмунд', 1904);
INSERT INTO book (title, author, year) VALUES ('День опричника', 'Владимир Сорокин', 2006);