CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) NOT NULL UNIQUE,
    year_of_birth int NOT NULL
);

CREATE TABLE Book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year int NOT NULL,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    taken_at timestamp
);

insert into person (full_name, year_of_birth) VALUES ('Иванов Иван Иванович', 1968);
insert into person (full_name, year_of_birth) VALUES ('Петров Петр Петрович', 1990);
insert into person (full_name, year_of_birth) VALUES ('Олегов Олег Олегович', 1990);

insert into book (title, author, year) VALUES ('Бытие и время',	'Мартин Хайдеггер',	1927);
insert into book (title, author, year) VALUES ('Философия Java', 'Брюс Эккель',	2018);
insert into book (title, author, year) VALUES ('Игра в бисер', 'Герман Гессе',	1943);
insert into book (title, author, year) VALUES ('Тайные виды на гору Фудзи',	'Владимир Пелевин',	2018);
insert into book (title, author, year) VALUES ('Над пропастью во ржи', 'Джером Сэллинджер', 1951);
insert into book (title, author, year) VALUES ('Психология обыденной жизни', 'Фрейд Зигмунд', 1904);
insert into book (title, author, year) VALUES ('День опричника', 'Владимир Сорокин', 2006);